### PR TITLE
Fix piping input from json

### PR DESCRIPTION
**Pull request by DrSensor**
## Description

This PR will enable the CLI to accept json from `process.stdin`
```bash
echo '{"states":[]}' | ./bin/smcat
```

## Motivation and Context
Currently, this is what happens:
```console
$ echo '{"states":[]}' | smcat

syntax error on line 1, column 1:
Expected comment, end of input, line end, or whitespace but "{" found.
```

## How Has This Been Tested?
(Testing CLI apps is always tricky, especially this one which I don't know how to do it. Please let me know if you have some tips 🙂)

## Screenshots (if appropriate):
<details><summary>Before</summary>

Peek 2019-06-17 07-02
</details>
<details><summary>After</summary>

Peek 2019-06-17 07-06
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] The code I add will be subject to [The MIT license](../LICENSE), and I'm OK with that.
- [x] The code I've added is my own original work.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](./CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by sverweij** [comment]
hi @DrSensor - thanks for this PR. Before I dive into the details - have you tried using `--input-type` on the command line? e.g. 

```sh
echo '{"states":[]}' | ./bin/smcat --input-type json
```

**Comment by sverweij** [comment]
Dôh - I now see; smcat ignores the `--input-type` option altogether, reading from stdin or otherwise.

**Comment by sverweij** [comment]
... that means this PR is not going to work, until that is fixed. I've created an issue (#57) and a fix for it (#58)

**Comment by DrSensor** [comment]
Thanks, that will do. I will close this now

**Pull request closed without merging**
